-- migrations/009_multi_pays_lots.sql
-- Lot 0 : Conception multi-pays et multilingue

ALTER TABLE etudes ADD COLUMN IF NOT EXISTS pays VARCHAR(10) NOT NULL DEFAULT 'ci';
ALTER TABLE etudes ADD COLUMN IF NOT EXISTS langue VARCHAR(10) NOT NULL DEFAULT 'fr';
ALTER TABLE etudes ADD COLUMN IF NOT EXISTS pack_regional VARCHAR(30) DEFAULT 'ohada-uemoa';
ALTER TABLE etudes ADD COLUMN IF NOT EXISTS fuseau_horaire VARCHAR(50) DEFAULT 'Africa/Abidjan';
ALTER TABLE etudes ADD COLUMN IF NOT EXISTS indicatif_tel VARCHAR(10) DEFAULT '+225';
ALTER TABLE etudes ADD COLUMN IF NOT EXISTS devise_code VARCHAR(10) DEFAULT 'XOF';
ALTER TABLE etudes ADD COLUMN IF NOT EXISTS devise_symbole VARCHAR(10) DEFAULT 'FCFA';

ALTER TABLE parametres_etude ADD COLUMN IF NOT EXISTS pays VARCHAR(10) DEFAULT 'ci';
ALTER TABLE parametres_etude ADD COLUMN IF NOT EXISTS langue VARCHAR(10) DEFAULT 'fr';
ALTER TABLE parametres_etude ADD COLUMN IF NOT EXISTS devise_code VARCHAR(10) DEFAULT 'XOF';
ALTER TABLE parametres_etude ADD COLUMN IF NOT EXISTS devise_symbole VARCHAR(10) DEFAULT 'FCFA';

ALTER TABLE dossiers ADD COLUMN IF NOT EXISTS devise_code VARCHAR(10) DEFAULT 'XOF';
ALTER TABLE dossiers ADD COLUMN IF NOT EXISTS bareme_version_id VARCHAR(50);
